// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solpositionCppv
List solpositionCppv(double lat, double lon, IntegerVector year, IntegerVector month, IntegerVector day, NumericVector hour);
RcppExport SEXP _trunktemp_solpositionCppv(SEXP latSEXP, SEXP lonSEXP, SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hour(hourSEXP);
    rcpp_result_gen = Rcpp::wrap(solpositionCppv(lat, lon, year, month, day, hour));
    return rcpp_result_gen;
END_RCPP
}
// onestepcpp
NumericMatrix onestepcpp(double Rdirdown, double Rdifdown, double Rswup, double Rlwup, double Rlwdown, double zen, double azi, double tair, double windspeed, double relhum, double pk, double refl, double em, double treeradius, double surfwet, NumericMatrix ptemps, NumericVector kwood, NumericVector ldist, NumericVector sdist, NumericVector heatcap, int timestep);
RcppExport SEXP _trunktemp_onestepcpp(SEXP RdirdownSEXP, SEXP RdifdownSEXP, SEXP RswupSEXP, SEXP RlwupSEXP, SEXP RlwdownSEXP, SEXP zenSEXP, SEXP aziSEXP, SEXP tairSEXP, SEXP windspeedSEXP, SEXP relhumSEXP, SEXP pkSEXP, SEXP reflSEXP, SEXP emSEXP, SEXP treeradiusSEXP, SEXP surfwetSEXP, SEXP ptempsSEXP, SEXP kwoodSEXP, SEXP ldistSEXP, SEXP sdistSEXP, SEXP heatcapSEXP, SEXP timestepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Rdirdown(RdirdownSEXP);
    Rcpp::traits::input_parameter< double >::type Rdifdown(RdifdownSEXP);
    Rcpp::traits::input_parameter< double >::type Rswup(RswupSEXP);
    Rcpp::traits::input_parameter< double >::type Rlwup(RlwupSEXP);
    Rcpp::traits::input_parameter< double >::type Rlwdown(RlwdownSEXP);
    Rcpp::traits::input_parameter< double >::type zen(zenSEXP);
    Rcpp::traits::input_parameter< double >::type azi(aziSEXP);
    Rcpp::traits::input_parameter< double >::type tair(tairSEXP);
    Rcpp::traits::input_parameter< double >::type windspeed(windspeedSEXP);
    Rcpp::traits::input_parameter< double >::type relhum(relhumSEXP);
    Rcpp::traits::input_parameter< double >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< double >::type refl(reflSEXP);
    Rcpp::traits::input_parameter< double >::type em(emSEXP);
    Rcpp::traits::input_parameter< double >::type treeradius(treeradiusSEXP);
    Rcpp::traits::input_parameter< double >::type surfwet(surfwetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ptemps(ptempsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kwood(kwoodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ldist(ldistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdist(sdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heatcap(heatcapSEXP);
    Rcpp::traits::input_parameter< int >::type timestep(timestepSEXP);
    rcpp_result_gen = Rcpp::wrap(onestepcpp(Rdirdown, Rdifdown, Rswup, Rlwup, Rlwdown, zen, azi, tair, windspeed, relhum, pk, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep));
    return rcpp_result_gen;
END_RCPP
}
// burnincpp
NumericMatrix burnincpp(DataFrame microclim, int reps, double refl, double em, double treeradius, double surfwet, NumericMatrix ptemps, NumericVector kwood, NumericVector ldist, NumericVector sdist, NumericVector heatcap, int timestep);
RcppExport SEXP _trunktemp_burnincpp(SEXP microclimSEXP, SEXP repsSEXP, SEXP reflSEXP, SEXP emSEXP, SEXP treeradiusSEXP, SEXP surfwetSEXP, SEXP ptempsSEXP, SEXP kwoodSEXP, SEXP ldistSEXP, SEXP sdistSEXP, SEXP heatcapSEXP, SEXP timestepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type microclim(microclimSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< double >::type refl(reflSEXP);
    Rcpp::traits::input_parameter< double >::type em(emSEXP);
    Rcpp::traits::input_parameter< double >::type treeradius(treeradiusSEXP);
    Rcpp::traits::input_parameter< double >::type surfwet(surfwetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ptemps(ptempsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kwood(kwoodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ldist(ldistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdist(sdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heatcap(heatcapSEXP);
    Rcpp::traits::input_parameter< int >::type timestep(timestepSEXP);
    rcpp_result_gen = Rcpp::wrap(burnincpp(microclim, reps, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep));
    return rcpp_result_gen;
END_RCPP
}
// runmodelcpp
NumericMatrix runmodelcpp(DataFrame microclim, int n, double refl, double em, double treeradius, double surfwet, NumericMatrix ptemps, NumericVector kwood, NumericVector ldist, NumericVector sdist, NumericVector heatcap, int timestep);
RcppExport SEXP _trunktemp_runmodelcpp(SEXP microclimSEXP, SEXP nSEXP, SEXP reflSEXP, SEXP emSEXP, SEXP treeradiusSEXP, SEXP surfwetSEXP, SEXP ptempsSEXP, SEXP kwoodSEXP, SEXP ldistSEXP, SEXP sdistSEXP, SEXP heatcapSEXP, SEXP timestepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type microclim(microclimSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type refl(reflSEXP);
    Rcpp::traits::input_parameter< double >::type em(emSEXP);
    Rcpp::traits::input_parameter< double >::type treeradius(treeradiusSEXP);
    Rcpp::traits::input_parameter< double >::type surfwet(surfwetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ptemps(ptempsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kwood(kwoodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ldist(ldistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdist(sdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heatcap(heatcapSEXP);
    Rcpp::traits::input_parameter< int >::type timestep(timestepSEXP);
    rcpp_result_gen = Rcpp::wrap(runmodelcpp(microclim, n, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep));
    return rcpp_result_gen;
END_RCPP
}
// runmodelthroughtime
NumericVector runmodelthroughtime(DataFrame microclim, int seg, int lyr, double refl, double em, double treeradius, double surfwet, NumericMatrix ptemps, NumericVector kwood, NumericVector ldist, NumericVector sdist, NumericVector heatcap, int timestep);
RcppExport SEXP _trunktemp_runmodelthroughtime(SEXP microclimSEXP, SEXP segSEXP, SEXP lyrSEXP, SEXP reflSEXP, SEXP emSEXP, SEXP treeradiusSEXP, SEXP surfwetSEXP, SEXP ptempsSEXP, SEXP kwoodSEXP, SEXP ldistSEXP, SEXP sdistSEXP, SEXP heatcapSEXP, SEXP timestepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type microclim(microclimSEXP);
    Rcpp::traits::input_parameter< int >::type seg(segSEXP);
    Rcpp::traits::input_parameter< int >::type lyr(lyrSEXP);
    Rcpp::traits::input_parameter< double >::type refl(reflSEXP);
    Rcpp::traits::input_parameter< double >::type em(emSEXP);
    Rcpp::traits::input_parameter< double >::type treeradius(treeradiusSEXP);
    Rcpp::traits::input_parameter< double >::type surfwet(surfwetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ptemps(ptempsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kwood(kwoodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ldist(ldistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdist(sdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heatcap(heatcapSEXP);
    Rcpp::traits::input_parameter< int >::type timestep(timestepSEXP);
    rcpp_result_gen = Rcpp::wrap(runmodelthroughtime(microclim, seg, lyr, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep));
    return rcpp_result_gen;
END_RCPP
}
// satvapCpp
NumericVector satvapCpp(NumericVector tc);
RcppExport SEXP _trunktemp_satvapCpp(SEXP tcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tc(tcSEXP);
    rcpp_result_gen = Rcpp::wrap(satvapCpp(tc));
    return rcpp_result_gen;
END_RCPP
}
// solarindexarray
NumericVector solarindexarray(IntegerVector year, IntegerVector month, IntegerVector day, NumericVector hour, NumericMatrix lats, NumericMatrix lons);
RcppExport SEXP _trunktemp_solarindexarray(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP, SEXP latsSEXP, SEXP lonsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hour(hourSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lons(lonsSEXP);
    rcpp_result_gen = Rcpp::wrap(solarindexarray(year, month, day, hour, lats, lons));
    return rcpp_result_gen;
END_RCPP
}
// blendtempCpp
NumericVector blendtempCpp(NumericVector tasmin, NumericVector tasmax, NumericVector temp);
RcppExport SEXP _trunktemp_blendtempCpp(SEXP tasminSEXP, SEXP tasmaxSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(blendtempCpp(tasmin, tasmax, temp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_trunktemp_solpositionCppv", (DL_FUNC) &_trunktemp_solpositionCppv, 6},
    {"_trunktemp_onestepcpp", (DL_FUNC) &_trunktemp_onestepcpp, 21},
    {"_trunktemp_burnincpp", (DL_FUNC) &_trunktemp_burnincpp, 12},
    {"_trunktemp_runmodelcpp", (DL_FUNC) &_trunktemp_runmodelcpp, 12},
    {"_trunktemp_runmodelthroughtime", (DL_FUNC) &_trunktemp_runmodelthroughtime, 13},
    {"_trunktemp_satvapCpp", (DL_FUNC) &_trunktemp_satvapCpp, 1},
    {"_trunktemp_solarindexarray", (DL_FUNC) &_trunktemp_solarindexarray, 6},
    {"_trunktemp_blendtempCpp", (DL_FUNC) &_trunktemp_blendtempCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_trunktemp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
