# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solpositionCppv <- function(lat, lon, year, month, day, hour) {
    .Call('_trunktemp_solpositionCppv', PACKAGE = 'trunktemp', lat, lon, year, month, day, hour)
}

onestepcpp <- function(Rdirdown, Rdifdown, Rswup, Rlwup, Rlwdown, zen, azi, tair, windspeed, relhum, pk, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep) {
    .Call('_trunktemp_onestepcpp', PACKAGE = 'trunktemp', Rdirdown, Rdifdown, Rswup, Rlwup, Rlwdown, zen, azi, tair, windspeed, relhum, pk, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep)
}

burnincpp <- function(microclim, reps, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep) {
    .Call('_trunktemp_burnincpp', PACKAGE = 'trunktemp', microclim, reps, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep)
}

runmodelcpp <- function(microclim, n, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep) {
    .Call('_trunktemp_runmodelcpp', PACKAGE = 'trunktemp', microclim, n, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep)
}

runmodelthroughtime <- function(microclim, seg, lyr, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep) {
    .Call('_trunktemp_runmodelthroughtime', PACKAGE = 'trunktemp', microclim, seg, lyr, refl, em, treeradius, surfwet, ptemps, kwood, ldist, sdist, heatcap, timestep)
}

satvapCpp <- function(tc) {
    .Call('_trunktemp_satvapCpp', PACKAGE = 'trunktemp', tc)
}

solarindexarray <- function(year, month, day, hour, lats, lons) {
    .Call('_trunktemp_solarindexarray', PACKAGE = 'trunktemp', year, month, day, hour, lats, lons)
}

blendtempCpp <- function(tasmin, tasmax, temp) {
    .Call('_trunktemp_blendtempCpp', PACKAGE = 'trunktemp', tasmin, tasmax, temp)
}

